apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ai-backend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ai-backend
  policy:
    semver:
      range: '>=1.0.0'