apiVersion: v1
kind: ConfigMap
metadata:
  name: nest-config
  namespace: publikationsempfehlung
data:
  APP_ENV: dev
  BACKEND_PORT: "3000"
  DB_HOST: postgres-service
  DB_USERNAME: root
  DB_DATABASE: pr
  DB_PASSWORD: secret
  DB_PORT: "5432"
  JWT_ACCESS_TOKEN_TTL: "900"
  JWT_REFRESH_TOKEN_TTL: "3600"
  PROJECT_AI_BACKEND_URL: http://ai-backend-service:8000
  PROJECT_FRONTEND_URL: http://papermatcher.com
  RABBITMQ_HOST: rabbitmq-service
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE1: queue1
  RABBITMQ_QUEUE2: queue2
  JWT_SECRET: secret
