apiVersion: v1
kind: Service
metadata:
  name: nest-service
  namespace: publikationsempfehlung
spec:
  selector:
    app: nest
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 
  type: LoadBalancer 