apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-source-pv
  namespace: publikationsempfehlung
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/backend-source"
