version: "3.9"
services:
  nest:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
