version: "3.9"
services:
  nest:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app/backend
      - ignore_backend:/usr/src/app/backend/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"

  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app/frontend
      - ignore_frontend:/usr/src/app/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true

volumes:
  ignore_backend:
  ignore_frontend:
