import * as Types from '../types.generated';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetPublicationGroupsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetPublicationGroupsQuery = { __typename?: 'Query', publicationGroups: Array<{ __typename?: 'PublicationGroupResponseDto', id: string, color: string, name: string, publications: Array<{ __typename?: 'PublicationResponseDto', id: string, title: string, source: Types.PublicationSource, doi: Array<string>, url?: string | null, authors?: Array<string> | null, publicationDate?: any | null, abstract?: string | null, exId: string, isFavorite: boolean, coordinate?: Array<number> | null, embeddings: Array<{ __typename?: 'EmbeddingResponseDto', text: string, vector: Array<number> }> }> }> };


export const GetPublicationGroupsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetPublicationGroups"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"publicationGroups"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"color"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"publications"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"source"}},{"kind":"Field","name":{"kind":"Name","value":"doi"}},{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"authors"}},{"kind":"Field","name":{"kind":"Name","value":"publicationDate"}},{"kind":"Field","name":{"kind":"Name","value":"abstract"}},{"kind":"Field","name":{"kind":"Name","value":"exId"}},{"kind":"Field","name":{"kind":"Name","value":"isFavorite"}},{"kind":"Field","name":{"kind":"Name","value":"coordinate"}},{"kind":"Field","name":{"kind":"Name","value":"embeddings"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"text"}},{"kind":"Field","name":{"kind":"Name","value":"vector"}}]}}]}}]}}]}}]} as unknown as DocumentNode<GetPublicationGroupsQuery, GetPublicationGroupsQueryVariables>;