import * as Types from '../types.generated';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetSimilarPublicationsForPublicationWithIdQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
  sortStrategy: Types.SortStrategy;
  page: Types.Scalars['Int'];
  amountPerPage: Types.Scalars['Int'];
}>;


export type GetSimilarPublicationsForPublicationWithIdQuery = { __typename?: 'Query', similarPublicationsForPublicationWithId: { __typename?: 'PublicationsSearchByIdResponseDto', similarPublications: Array<{ __typename?: 'PublicationResponseDto', id: string, title: string, source: Types.PublicationSource, doi: Array<string>, url?: string | null, authors?: Array<string> | null, publicationDate?: any | null, abstract?: string | null }> } };


export const GetSimilarPublicationsForPublicationWithIdDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetSimilarPublicationsForPublicationWithId"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"sortStrategy"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"SortStrategy"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"page"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"amountPerPage"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"similarPublicationsForPublicationWithId"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"similarPublicationsForPublicationWithIdDto"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"sortStrategy"},"value":{"kind":"Variable","name":{"kind":"Name","value":"sortStrategy"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"page"},"value":{"kind":"Variable","name":{"kind":"Name","value":"page"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"amountPerPage"},"value":{"kind":"Variable","name":{"kind":"Name","value":"amountPerPage"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"similarPublications"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"source"}},{"kind":"Field","name":{"kind":"Name","value":"doi"}},{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"authors"}},{"kind":"Field","name":{"kind":"Name","value":"publicationDate"}},{"kind":"Field","name":{"kind":"Name","value":"abstract"}}]}}]}}]}}]} as unknown as DocumentNode<GetSimilarPublicationsForPublicationWithIdQuery, GetSimilarPublicationsForPublicationWithIdQueryVariables>;