query GetSearchResults(
  $query: String!
  $sortStrategy: SortStrategy!
  $page: Int!
  $amountPerPage: Int!
  $filters: SearchFilters
) {
  publications(
    publicationsSearchDto: {
      searchInput: $query
      sortStrategy: $sortStrategy
      page: $page
      amountPerPage: $amountPerPage
      filters: $filters
    }
  ) {
    matchingPublications {
      id
      title
      source
      doi
      url
      authors
      publicationDate
      abstract
    },
    similarPublications {
      id
      title
      source
      doi
      url
      authors
      publicationDate
      abstract
    }
  }
}
