import * as Types from '../types.generated';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetSimilarPublicationsForPublicationWithIdCoordinatesQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
  page: Types.Scalars['Int'];
  amountPerPage: Types.Scalars['Int'];
}>;


export type GetSimilarPublicationsForPublicationWithIdCoordinatesQuery = { __typename?: 'Query', similarPublicationsForPublicationWithId: { __typename?: 'PublicationsSearchByIdResponseDto', searchCoordinate?: Array<number> | null, similarPublications: Array<{ __typename?: 'PublicationResponseDto', id: string, title: string, source: Types.PublicationSource, doi: Array<string>, url?: string | null, authors?: Array<string> | null, publicationDate?: any | null, abstract?: string | null, coordinate?: Array<number> | null }> } };


export const GetSimilarPublicationsForPublicationWithIdCoordinatesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetSimilarPublicationsForPublicationWithIdCoordinates"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"page"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"amountPerPage"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"similarPublicationsForPublicationWithId"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"similarPublicationsForPublicationWithIdDto"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"page"},"value":{"kind":"Variable","name":{"kind":"Name","value":"page"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"amountPerPage"},"value":{"kind":"Variable","name":{"kind":"Name","value":"amountPerPage"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"searchCoordinate"}},{"kind":"Field","name":{"kind":"Name","value":"similarPublications"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"source"}},{"kind":"Field","name":{"kind":"Name","value":"doi"}},{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"authors"}},{"kind":"Field","name":{"kind":"Name","value":"publicationDate"}},{"kind":"Field","name":{"kind":"Name","value":"abstract"}},{"kind":"Field","name":{"kind":"Name","value":"coordinate"}}]}}]}}]}}]} as unknown as DocumentNode<GetSimilarPublicationsForPublicationWithIdCoordinatesQuery, GetSimilarPublicationsForPublicationWithIdCoordinatesQueryVariables>;