version: '3.9'
services:
  node:
    image: node:18-alpine3.17
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    working_dir: /usr/src/app
    networks:
      - network

  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    networks:
      - network

networks:
  network:
    name: network
