FROM node:18-alpine3.17
WORKDIR /usr/src/app/backend
EXPOSE 3001
RUN apk --no-cache add curl
HEALTHCHECK --interval=5s --timeout=5s --start-period=10s --retries=3 CMD ["curl","--fail","localhost:3000"]
COPY package.json package-lock.json ./
RUN npm install
COPY ./ ./
RUN npm run build
CMD ["npm","run", "start"]
