version: '3.9'
services:
  node:
    image: node:18-alpine3.17
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    stdin_open: true
    tty: true
    working_dir: /usr/src/app
    networks:
      - network

  mongo:
    image: mongo:7.0.2
    volumes:
      - ./mongo:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    ports:
        - "27017:27017"
    networks:
      - network

networks:
  network:
    name: network
