apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: publikationsempfehlung
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: db
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: management
  type: ClusterIP

