apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: data-ingest
  namespace: flux-system
spec:
  image: hrabar.azurecr.io/ki-publikationsempfehlung-data-ingest
  interval: 1m
  secretRef:
    name: regcred