apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: data-ingest-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: data-ingest
  policy:
    semver:
      range: '>=1.0.0'